---
title: Exercices corrigés du chapitre 9
author: Yves Croissant
output: 
  html_document:
    toc: true
    toc_float: true
  pdf_document:
    number_sections: true
vignette: >
  %\VignetteEncoding{UTF-8}
  %\VignetteIndexEntry{Exercices corrigés du chapitre 9}
  %\VignetteEngine{knitr::rmarkdown}
---

### Exercice 1 {-}

#### Intitulé

On considère la démarche de recherche de stage par des
étudiants. Celle-ci peut être fructueuse (l'étudiant trouve un stage)
ou infructueuse. On note $E$ et $\bar{E}$ ces deux évènements. Dans
certains cas, l'entreprise sollicitée demande à l'étudiant un
complément d'informations sur sa candidature. On note $I$ cet
évènement et $\bar{I}$ l'évènement correspondant à une non-demande
d'informations complémentaires. À partir de l'expérience des années
antérieures, on a déterminé que :

- la probabilité qu'une candidature à un stage soit fructueuse est de
  20%,
- l'entreprise contactée demande des informations complémentaires dans
  75% des cas lorsque l'entreprise recrute l'étudiant pour un stage,
- l'entreprise contactée demande des informations complémentaires dans
  18.75% des cas lorsque l'entreprise ne recrute pas l'étudiant pour un
  stage.
  
1. Quelle est la probabilité que la recherche de stage soit fructueuse
et que des informations supplémentaires soient demandées.  Même
question lorsqu'aucune information supplémentaire n'est demandée.
1. Quelle est la probabilité qu'une information complémentaire soit
demandée par l'entreprise ?
1. Un étudiant reçoit une demande d'informations complémentaires de la
part de l'entreprise. Quelle est alors la probabilité que sa
candidature soit fructueuse ?

#### Corrigé

**Q1.** La probabilité jointe s'écrit\ : $P(E \cap I)$. On peut
l'écrire comme le produit d'une probabilité conditionnelle et d'une
probabilité marginale. On connaît ici la probabilité que la
candidature soit fructueuse ($P(E) = 0.2$) et la probabilité qu'une
demande d'informations complémentaires soit faite sachant que la
candidature est finalement acceptée ($P(I \mid E)=0.75$). On obtient
finalement\ : $P(E \cap I) = P(I \mid E) \times P(E) = 0.75 \times
0.2= 0.15$. De la même manière\ : $P(\bar{E} \cap I) = P(I \mid
\bar{E}) \times P(\bar{E}) = 0.1875 \times 0.8= 0.15$.

**Q2.** La probabilité marginale qu'une information complémentaire
soit demandée est la somme des deux probabilités jointes précédemment
calculées, soit\ : $P(I) = P(E \cap I) + P(E \cap \bar{I}) = 0.15 +
0.15 = 0.3$.

**Q3.** Si l'étudiant a reçu une demande d'informations
complémentaire, la probabilité que sa demande de stage soit fructueuse
est la probabilité conditionnelle\ : $P(E \mid I) = \frac{P(E \cap
I)}{P(I)} = \frac{0.15}{0.3}=0.5$. Dans la terminologie de la
statistique bayesienne, la probabilité *a priori* que la demande de
stage soit fructueuse est de 20% alors que la probabilité *a
posteriori* (l'entreprise a demandé des informations complémentaires)
est de 50%. En revanche, s'il n'y a pas eu demande d'informations
complémentaires, la probabilité *a posteriori* est $P(E \mid \bar{I})
= \frac{P(E \cap \bar{I})}{P(\bar{I})} = \frac{0.05}{0.7}=0.071$, soit
7.1%.


### Exercice 2 {-}

#### Intitulé

Le loto français consiste à remplir une grille\ :

- en choisissant 5 numéros parmi les nombres de 1 à 49,
- en choisissant 1 numéro (appelé "numéro chance") parmi les nombres
  de 1 à 19.

Le gain maximum est obtenu si le joueur a choisi les 5 bons numéros et
le numéro chance. Une grille est gagnante si\ :

- le numéro chance est choisi,
- au moins deux bons numéros sont choisis. 

1. Quelle est la probabilité d'obtenir les 5 bons numéros ?
1. Quelle est la probabilité d'obtenir les 5 bons numéros et le numéro
chance ? Même question pour les 5 bons numéros sans le numéro chance ?
1. Quelle est la probabilité d'obtenir 4 bons numéros ?
1. Quelle est la probabilité d'obtenir 3 bons numéros ?
1. Quelle est la probabilité de ne rien gagner ?

Pour illustrer vos réponses, vous pouvez prendre l'exemple où le
tirage des 5 numéros donne 1, 2, 3, 4, 5.

#### Corrigé

```{r echo = FALSE}
fmt <- function(x) format(x, scientific = FALSE, big.mark = " ")
prob5 <- format(round(1 / choose(49,5) * 100, 6), scientific = FALSE, small.mark = "\  ", small.interval = 3)
prob5C <- format(round(1 / choose(49,5) * 10, 6), scientific = FALSE, small.mark = "\  ", small.interval = 3)
prob5S <- format(round(1 / choose(49,5) * 90, 6), scientific = FALSE, small.mark = "\  ", small.interval = 3)
prob4 <- format(round(220 / choose(49,5) * 100, 4), scientific = FALSE, small.mark = "\  ", small.interval = 3)
prob1 <- format(round(5 * choose(44, 4) / choose(49,5) * 100, 2), scientific = FALSE, small.mark = "\  ", small.interval = 3)
prob0 <- format(round(choose(44, 5) / choose(49, 5) * 100, 2), scientific = FALSE, small.mark = "\  ", small.interval = 3)
```
**Q1.** En utilisant la
règle de comptage par combinaison, on a $\frac{49 !}{5 ! 44!} =$ 
`r fmt(choose(49, 5))` combinaisons possibles de 5 numéros. Chaque
numéro ayant la même probabilité de sortir, toutes ces combinaisons
sont équiprobables. La probabilité associée à la bonne combinaison des 5
numéros est donc $P(B_5) = \frac{1}{`r fmt(choose(49, 5))`} = `r prob5`$%.


**Q2.** Le numéro chance est celui indiqué sur une boule
parmi 10. Chaque boule ayant la même probabilité d'être tirée, il y a
donc une probabilité de P(C) = $0.1$ d'avoir le numéro chance et une
probabilité de $P(\bar{C}) = 0.9$ de ne pas l'avoir. La probabilité
d'avoir les 5 bons numéros et le numéro chance est la probabilité
jointe $P(B_5 \cap C)$. Or, le tirage du numéro chance est indépendant
du tirage des 5 numéros ; par conséquent, cette probabilité jointe est
le produit des deux probabilités marginales, soit\ :
$P(B_5 \cap C) = P(B_5) \times P(C) = `r prob5` \times 0.1 =
`r prob5C`$%. De la même manière, la probabilité d'obtenir les 5 bons
numéros, mais pas le numéro chance est\ :
$P(B_5 \cap \bar{C}) = P(B_5) \times P(\bar{C}) = `r prob5` \times 0.9 =
`r prob5S`$%.

**Q3.** Pour calculer la probabilité d'avoir quatre bons numéros, on
considère le sous-ensemble des combinaisons qui correspond à ce
cas. Il y a $C^4_5=5$ combinaisons de 4 bons numéros possibles, par
exemple 1, 2, 3, 4. En termes de tirage (5 boules), on a pour chacune
de ces combinaisons 44 possibilités (c'est-à-dire autant que de
numéros non gagnants\ : (1, 2, 3, 4, 6), (1, 2, 3, 4, 7), etc). Il y a
donc $5 \times 44 = 220$ combinaisons de 5 boules qui correspondent à
4 bons numéros. La probabilité associée est donc\ :

$\frac{C_5^4 \times 44}{C_{49}^5}=
\frac{220}{`r fmt(choose(49, 5))`} = `r fmt(round(220 / choose(49,5) * 100, 6))`$%.


**Q4.** Il y a $C^3_5=`r choose(5,3)`$ combinaisons possibles de 3
bons numéros. Comme on tire 5 boules, il faut rajouter au 3 numéros
gagnants 2 numéros perdants. Il y a 44 numéros perdants et 
$C^2_{44} = `r choose(44, 2)`$ combinaisons possibles de 2 numéros
perdants. On a donc $`r choose(5,3)` \times `r choose(44, 2)` =$
`r fmt(choose(5, 3) * choose(44, 2))` combinaisons de 5 numéros contenant 3
bons numéros. La probabilité est donc\ :
$\frac{C_5^3 \times C_{44}^2}{C_{49}^5}=
\frac{`r fmt(choose(5, 3))` \times `r fmt(choose(44, 2))`}
{`r fmt(choose(49, 5))`} = `r fmt(round(choose(5, 3) * choose(44, 2) / choose(49,5) * 100, 4))`$%.

**Q5.** La probabilité d'avoir un numéro gagnant s'obtient en comptant
les combinaisons qui contiennent 1 bon numéro parmi 5 et 4 mauvais
(nombre de combinaisons de 4 numéros parmi 44, soit `r fmt(choose(44, 4))`). 
On a donc $5 \times$ `r fmt(choose(44, 4))` = 
`r fmt(5 * choose(44, 4))` combinaisons
et une probabilité de $\frac{5 \times C_{44}^4}{C_{49}^5}=`r prob1`$%.

Pour calculer la probabilité de n'avoir aucun numéro gagnant, on calcule
le nombre de combinaisons de 5 numéros parmi 44 (les 44 numéros
perdants) $C^5_{44} =$ `r fmt(choose(44, 5))`  et la probabilité associée
$\frac{C^5_{44}}{C^5_{49}}=`r prob0`$%.

La probabilité de ne rien gagner est la somme de la probabilité d'avoir
0 ou 1  numéro gagnant et de ne pas avoir le numéro chance. Cette
probabilité jointe est égale au produit des deux probabilités
marginales car les deux évènements sont indépendants\ :
$(`r prob0` + `r prob1`) \times 0.9 = 
`r round((5 * choose(44, 4) / choose(49,5) + choose(44, 5) / choose(49, 5)) * 90, 2)`$%.
